### PR TITLE
pkg: updated dependency

### PR DESCRIPTION
**Pull request by rojii**
Although, the bcstring repo hasn't been published with the new CashAddr file in the current version available on npm; It will eventually be updated and this a simple update. 

This is necessary for adding CashAddresses to the primitives library. So this is the first step in this process.

### CODE REVIEW

**Comment by nodar-chkuaselidze** [comment]
Thanks, published bcstring

**Comment by nodar-chkuaselidze** [comment]
I reverted this changes, until whole wallet and address changes are pushed.

**Comment by rojii** [comment]
Understood but it shouldn't break anything. I'll get to work on the primitives library today.

**Comment by nodar-chkuaselidze** [comment]
It will break many tests and also I have bunch of changes that I have not pushed yet, that kindof overlap with the changes that are necessary. Primitives included.

**Comment by rojii** [comment]
Okay, understood.

**Pull request merged**
