### PR TITLE
bcash: upgrade to modern dependencies.

### PR DESCRIPTION
**Pull request by chjj**
This upgrades to a more modern version of BDB and bcrypto. Both of them now have their dependencies vendored for security. There's some minor API changes as well, mostly involving database keys.

Also, we should no longer use the built-in node.js `assert` in production code. It will parse the JS file to try to display the offending line -- this is a DoS vector depending on where the assertion is. `bsert` is used instead.

### CODE REVIEW

**Comment by rojii** [comment]
The error is probably due to changing the dependency to bstring instead of bcstring.

**Comment by chjj** [comment]
@rojii, we merged in bcstring's changes to bstring.

**Comment by rojii** [comment]
@chjj, Ahh I missed that. I'll take a look and see if I can figure it out then.

**Comment by rojii** [comment]
I passed the same string into the Address library the Adress.fromCashAddr('bitcoincas:qrzhjdpv93xfygpqtckdc2zkzuzqeyj2pgkm0jl23k').

An error is returned indicating that the length of the string causes an error to be thrown as an Invalid Checksum. Basically the same test found checking for whether the prefix is valid is the same tests used right under for checking if the checksum is invalid. 

I assume the error is simply due to the message being returned doesn't match the one written in the primitives/address.js file.

**Pull request closed without merging**
